markdown: rdiscount
permalink: /:title/
url: http://github.thinkingbar.com
highlighter: pygments
name: 飘过的小牛
description: 飘过的小牛 | Stop talking, start doing.
author: niushuai
email: hnns1990@gmail.com
duoshuo: niushuai
weibo: 1891858481
hub: niushuai
safe: true
paginate: 100
about: "弱菜一枚。"
