markdown: rdiscount
permalink: /:title/
url: http://github.thinkingbar.com
highlighter: pygments
name: richard blog 
description: richard blog | Stop talking, start doing.
author: richard  
email: 364374779@qq.com
duoshuo: richard 
weibo: richard 
hub: richard2011 
safe: true
paginate: 100
about: "程序员一枚。"
